### ISSUE TITLE
Hi,I use your lib in android,but it crash.

### ISSUE THREAD

**Issue by atszgoogle** [jiechic/Snappy-Android#1]
Hi,I use you lib in android,but it crash.
FYI,
this is the log:
  Caused by: java.lang.ClassNotFoundException: Didn't find class "com.jiechic.library.android.snappy.Snappy" on path: DexPathList[[zip file "/data/app/org.semux-a3iMU_k-6IeNnrtTGMp_qQ==/base.apk", zip file "/data/app/org.semux-a3iMU_k-6IeNnrtTGMp_qQ==/split_lib_dependencies_apk.apk", zip file "/data/app/org.semux-a3iMU_k-6IeNnrtTGMp_qQ==/split_lib_slice_0_apk.apk", zip file "/data/app/org.semux-a3iMU_k-6IeNnrtTGMp_qQ==/split_lib_slice_1_apk.apk", zip file "/data/app/org.semux-a3iMU_k-6IeNnrtTGMp_qQ==/split_lib_slice_2_apk.apk", zip file "/data/app/org.semux-a3iMU_k-6IeNnrtTGMp_qQ==/split_lib_slice_3_apk.apk", zip file "/data/app/org.semux-a3iMU_k-6IeNnrtTGMp_qQ==/split_lib_slice_4_apk.apk", zip file "/data/app/org.semux-a3iMU_k-6IeNnrtTGMp_qQ==/split_lib_slice_5_apk.apk", zip file "/data/app/org.semux-a3iMU_k-6IeNnrtTGMp_qQ==/split_lib_slice_6_apk.apk", zip file "/data/app/org.semux-a3iMU_k-6IeNnrtTGMp_qQ==/split_lib_slice_7_apk.apk", zip file "/data/app/org.semux-a3iMU_k-6IeNnrtTGMp_qQ==/split_lib_slice_8_apk.apk", zip file "/data/app/org.semux-a3iMU_k-6IeNnrtTGMp_qQ==/split_lib_slice_9_apk.apk"],nativeLibraryDirectories=[/data/app/org.semux-a3iMU_k-6IeNnrtTGMp_qQ==/lib/x86, /data/app/org.semux-a3iMU_k-6IeNnrtTGMp_qQ==/base.apk!/lib/x86, /data/app/org.semux-a3iMU_k-6IeNnrtTGMp_qQ==/split_lib_dependencies_apk.apk!/lib/x86, /data/app/org.semux-a3iMU_k-6IeNnrtTGMp_qQ==/split_lib_slice_0_apk.apk!/lib/x86, /data/app/org.semux-a3iMU_k-6IeNnrtTGMp_qQ==/split_lib_slice_1_apk.apk!/lib/x86, /data/app/org.semux-a3iMU_k-6IeNnrtTGMp_qQ==/split_lib_slice_2_apk.apk!/lib/x86, /data/app/org.semux-a3iMU_k-6IeNnrtTGMp_qQ==/split_lib_slice_3_apk.apk!/lib/x86, /data/app/org.semux-a3iMU_k-6IeNnrtTGMp_qQ==/split_lib_slice_4_apk.apk!/lib/x86, /data/app/org.semux-a3iMU_k-6IeNnrtTGMp_qQ==/split_lib_slice_5_apk.apk!/lib/x86, /data/app/org.semux-a3iMU_k-6IeNnrtTGMp_qQ==/split_lib_slice_6_apk.apk!/lib/x86, /data/app/org.semux-a3iMU_k-6IeNnrtTGMp_qQ==/split_lib_slice_7_apk.apk!/lib/x86, /data/app/org.semux-a3iMU_k-6IeNnrtTGMp_qQ==/split_lib_slice_8_apk.apk!/lib/x86, /data/app/org.semux-a3iMU_k-6IeNnrtTGMp_qQ==/split_lib_slice_9_apk.apk!/lib/x86, /system/lib, /vendor/lib]]
                      at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:93)
                      at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
                      at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
                      at org.semux.MainActivity.onCreate(MainActivity.java:16) 
                      at android.app.Activity.performCreate(Activity.java:6975) 
                      at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1213) 
                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2770) 
                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2892) 
                      at android.app.ActivityThread.-wrap11(Unknown Source:0) 
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1593) 
                      at android.os.Handler.dispatchMessage(Handler.java:105) 
                      at android.os.Looper.loop(Looper.java:164) 
                      at android.app.ActivityThread.main(ActivityThread.java:6541) 
                      at java.lang.reflect.Method.invoke(Native Method) 
                      at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240) 
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)

**Comment by jiechic** [comment]
java.lang.ClassNotFoundException is class missing,
not .so didn't found , please check you pro guard,and check multi dex setting 

you can run the library sample use your data to check you phone

**Comment by atszgoogle** [comment]
sorry，guy，your sample also have problem。Can you check？
After i import the sample,Android Studio show 

Error:(1, 0) Plugin with id 'com.android.application' not found.

**Comment by jiechic** [comment]
I use code normally in my env，you can change android gradle plugin version in build.gradle to try to fix this problem in your env

**Comment by Qubitium** [comment]
We do not any issue using this library.
